export {default as Icon} from "./icon";

export {default as AddIcon} from "./addIcon";
export {default as ArrowBackIOSIcon} from "./arrowBackIOSIcon";
export {default as ArrowForwardIOSIcon} from "./arrowForwardIOSIcon";
export {default as CasesIcon} from "./casesIcon";
export {default as CloseIcon} from "./closeIcon";
export {default as ExpandIcon} from "./expandIcon";
export {default as ExpandLessIcon} from "./expandLessIcon";
export {default as ExpandMoreIcon} from "./expandMoreIcon";
export {default as FastForwardIcon} from "./fastForwardIcon";
export {default as FastRewindIcon} from "./fastRewindIcon";
export {default as GitHubIcon} from "./gitHubIcon";
export {default as HistoryIcon} from "./historyIcon";
export {default as HomeIcon} from "./homeIcon";
export {default as KeyboardArrowDown} from "./keyboardArrowDownIcon";
export {default as KeyboardArrowRight} from "./keyboardArrowRightIcon";
export {default as LinkedInIcon} from "./linkedInIcon";
export {default as OpenInNewIcon} from "./openInNewIcon";
export {default as PauseCircleIcon} from "./pauseCircleIcon";
export {default as PlayCircleIcon} from "./playCircleIcon";
export {default as PsychologyIcon} from "./psychologyIcon";
export {default as RestartAltIcon} from "./restartAltIcon";
export {default as RestoreIcon} from "./restoreIcon";
export {default as SadFaceEmojiIcon} from "./sadFaceEmojiIcon";
export {default as SettingsIcon} from "./settingsIcon";
export {default as WorkHistoryIcon} from "./workHistoryIcon";

export {IconColor, IconName, IconSize} from "./icon.constants";
export type {SVGIconProps} from "./icon.types";
