packages:
  # Applications (Pavilion, Lookbook, and all Gallery themes)
  - "apps/*"
  - "apps/galleries/**"

  # Core Infrastructure & UI
  - "packages/*"
allowBuilds:
  sharp: true
  unrs-resolver: true
