import { ComponentManifest } from "../components/types";

export type ComponentRegistryType = Record<string, () => Promise<{ manifest: ComponentManifest }>>;

const COMPONENT_REGISTRY: ComponentRegistryType = {
	Alert: () => import("../components/alert/alert.manifest").then(m => ({ manifest: m.default })),
	Backdrop: () => import("../components/backdrop/backdrop.manifest").then(m => ({ manifest: m.default })),
	Button: () => import("../components/button/button.manifest").then(m => ({ manifest: m.default })),
	ButtonBase: () => import("../components/buttonBase/buttonBase.manifest").then(m => ({ manifest: m.default })),
	Card: () => import("../components/card/card.manifest").then(m => ({ manifest: m.default })),
	CardActions: () => import("../components/card/cardActions.manifest").then(m => ({ manifest: m.default })),
	CardContent: () => import("../components/card/cardContent.manifest").then(m => ({ manifest: m.default })),
	CardHeader: () => import("../components/card/cardHeader.manifest").then(m => ({ manifest: m.default })),
	Checkbox: () => import("../components/checkbox/checkbox.manifest").then(m => ({ manifest: m.default })),
	Chip: () => import("../components/chip/chip.manifest").then(m => ({ manifest: m.default })),
	CopyButton: () => import("../components/copyButton/copyButton.manifest").then(m => ({ manifest: m.default })),
	Collapse: () => import("../components/collapse/collapse.manifest").then(m => ({ manifest: m.default })),
	Dropdown: () => import("../components/dropdown/dropdown.manifest").then(m => ({ manifest: m.default })),
	EditorShell: () => import("../components/editorShell/editorShell.manifest").then(m => ({ manifest: m.default })),
	EmailTextField: () => import("../components/emailTextField/emailTextField.manifest").then(m => ({ manifest: m.default })),
	ErrorBoundary: () => import("../components/errorBoundary/errorBoundary.manifest").then(m => ({ manifest: m.default })),
	Footer: () => import("../components/footer/footer.manifest").then(m => ({ manifest: m.default })),
	Heading: () => import("../components/heading/heading.manifest").then(m => ({ manifest: m.default })),
	Icon: () => import("../components/icon/icon.manifest").then(m => ({ manifest: m.default })),
	IconButton: () => import("../components/iconButton/iconButton.manifest").then(m => ({ manifest: m.default })),
	InlineButton: () => import("../components/inlineButton/inlineButton.manifest").then(m => ({ manifest: m.default })),
	InputIcon: () => import("../components/inputIcon/inputIcon.manifest").then(m => ({ manifest: m.default })),
	Label: () => import("../components/label/label.manifest").then(m => ({ manifest: m.default })),
	Link: () => import("../components/link/link.manifest").then(m => ({ manifest: m.default })),
	LinkButton: () => import("../components/linkButton/linkButton.manifest").then(m => ({ manifest: m.default })),
	List: () => import("../components/list/list.manifest").then(m => ({ manifest: m.default })),
	ListItem: () => import("../components/list/listItem.manifest").then(m => ({ manifest: m.default })),
	ListItemButton: () => import("../components/list/listItemButton.manifest").then(m => ({ manifest: m.default })),
	ListItemIcon: () => import("../components/list/listItemIcon.manifest").then(m => ({ manifest: m.default })),
	ListItemText: () => import("../components/list/listItemText.manifest").then(m => ({ manifest: m.default })),
	ListSubHeader: () => import("../components/list/listSubHeader.manifest").then(m => ({ manifest: m.default })),
	Menu: () => import("../components/menu/menu.manifest").then(m => ({ manifest: m.default })),
	MenuItem: () => import("../components/menuItem/menuItem.manifest").then(m => ({ manifest: m.default })),
	SearchField: () => import("../components/searchField/searchField.manifest").then(m => ({ manifest: m.default })),
	Section: () => import("../components/section/section.manifest").then(m => ({ manifest: m.default })),
	SectionHeading: () => import("../components/section/sectionHeading.manifest").then(m => ({ manifest: m.default })),
	Select: () => import("../components/select/select.manifest").then(m => ({ manifest: m.default })),
	StatusChip: () => import("../components/statusChip/statusChip.manifest").then(m => ({ manifest: m.default })),
	Surface: () => import("../components/surface/surface.manifest").then(m => ({ manifest: m.default })),
	Switch: () => import("../components/switch/switch.manifest").then(m => ({ manifest: m.default })),
	Tab: () => import("../components/tab/tab.manifest").then(m => ({ manifest: m.default })),
	Table: () => import("../components/table/table.manifest").then(m => ({ manifest: m.default })),
	TableBody: () => import("../components/table/tableBody.manifest").then(m => ({ manifest: m.default })),
	TableBodyCell: () => import("../components/table/tableBodyCell.manifest").then(m => ({ manifest: m.default })),
	TableHead: () => import("../components/table/tableHead.manifest").then(m => ({ manifest: m.default })),
	TableHeadCell: () => import("../components/table/tableHeadCell.manifest").then(m => ({ manifest: m.default })),
	TableRow: () => import("../components/table/tableRow.manifest").then(m => ({ manifest: m.default })),
	Tabs: () => import("../components/tabs/tabs.manifest").then(m => ({ manifest: m.default })),
	Text: () => import("../components/text/text.manifest").then(m => ({ manifest: m.default })),
	TextArea: () => import("../components/textArea/textArea.manifest").then(m => ({ manifest: m.default })),
	TextField: () => import("../components/textField/textField.manifest").then(m => ({ manifest: m.default })),
	ToggleIconButton: () => import("../components/toggleIconButton/toggleIconButton.manifest").then(m => ({ manifest: m.default })),
	Tooltip: () => import("../components/tooltip/tooltip.manifest").then(m => ({ manifest: m.default })),
	Typography: () => import("../components/typography/typography.manifest").then(m => ({ manifest: m.default }))
};

export default COMPONENT_REGISTRY;
