export {
	APP_MANIFEST_HELLOWORLD_CLASSIC,
	APP_MANIFEST_HELLOWORLD_COMPOSITE,
	APP_NAME_HELLOWORLD_CLASSIC,
	APP_NAME_HELLOWORLD_COMPOSITE
} from "./helloworld";
export type { AppNameGalleries } from "./appName";
