import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ReactNode } from "react";

import {PavilionProvider} from "@otuekong-portfolio/exhibit";

const geistSans = Geist({
	subsets: ["latin"],
  	variable: "--font-geist-sans"
});

const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono"
});

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App"
};

interface RootLayoutProps {
	children: ReactNode;
}

function RootLayout({
	children,
}: Readonly<RootLayoutProps>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<PavilionProvider>{children}</PavilionProvider>
			</body>
		</html>
	);
}

export default RootLayout;
