import {
	JSON_SCHEMA_PROPERTY_APP_NAME,
	JSON_SCHEMA_PROPERTY_CRON_SECRET,
	JSON_SCHEMA_PROPERTY_EMAIL,
	JSON_SCHEMA_PROPERTY_LOG_LEVEL,
	JSON_SCHEMA_PROPERTY_NODE_ENV,
	JSON_SCHEMA_PROPERTY_RESEND_API_KEY,
	JSON_SCHEMA_PROPERTY_UPSTASH_REDIS_REST_URL,
	JSON_SCHEMA_PROPERTY_UPSTASH_REDIS_REST_TOKEN
} from "../../common/schema";

const isBuildTime = process.env.NEXT_PHASE === "phase-production-build";

const RuntimeSchema = Object.freeze({
	$id: "pavilion-env-schema",
	type: "object",
	required: [
		"APP_NAME",
		"CRON_SECRET",
		"LOG_LEVEL",
		"NODE_ENV",
		"RESEND_API_KEY",
		"UPSTASH_REDIS_REST_URL",
		"UPSTASH_REDIS_REST_TOKEN"
	],
	properties: {
		APP_NAME: JSON_SCHEMA_PROPERTY_APP_NAME,
		CRON_SECRET: JSON_SCHEMA_PROPERTY_CRON_SECRET,
		LOG_LEVEL: JSON_SCHEMA_PROPERTY_LOG_LEVEL,
		LOG_CLIENT_LEVEL: JSON_SCHEMA_PROPERTY_LOG_LEVEL,
		LOG_SERVER_LEVEL: JSON_SCHEMA_PROPERTY_LOG_LEVEL,
		NODE_ENV: JSON_SCHEMA_PROPERTY_NODE_ENV,
		PORTFOLIO_EMAIL_SENDER: JSON_SCHEMA_PROPERTY_EMAIL,
		PORTFOLIO_EMAIL_TARGET: JSON_SCHEMA_PROPERTY_EMAIL,
		RESEND_API_KEY: JSON_SCHEMA_PROPERTY_RESEND_API_KEY,
		UPSTASH_REDIS_REST_URL: JSON_SCHEMA_PROPERTY_UPSTASH_REDIS_REST_URL,
		UPSTASH_REDIS_REST_TOKEN: JSON_SCHEMA_PROPERTY_UPSTASH_REDIS_REST_TOKEN
	}
} as const);

const BuildTimeSchema = Object.freeze({
	$id: "pavilion-env-schema",
	type: "object",
	required: ["NODE_ENV"],
	properties: {
		APP_NAME: JSON_SCHEMA_PROPERTY_APP_NAME,
		CRON_SECRET: { type: "string" },
		LOG_LEVEL: JSON_SCHEMA_PROPERTY_LOG_LEVEL,
		LOG_CLIENT_LEVEL: JSON_SCHEMA_PROPERTY_LOG_LEVEL,
		LOG_SERVER_LEVEL: JSON_SCHEMA_PROPERTY_LOG_LEVEL,
		NODE_ENV: JSON_SCHEMA_PROPERTY_NODE_ENV,
		PORTFOLIO_EMAIL_SENDER: { type: "string" },
		PORTFOLIO_EMAIL_TARGET: { type: "string" },
		RESEND_API_KEY: { type: "string" },
		UPSTASH_REDIS_REST_URL: { type: "string" },
		UPSTASH_REDIS_REST_TOKEN: { type: "string" }
	}
} as const);

const PavilionEnvironmentJsonSchema = isBuildTime ? BuildTimeSchema : RuntimeSchema;

export default PavilionEnvironmentJsonSchema;
