import { ElementType, lazy } from "react";

import {
	AlertCircleIcon,
	AlertTriangleIcon,
	Award,
	Book,
	Briefcase,
	Building2,
	Check,
	CheckCircle,
	ChevronDown,
	ChevronUp,
	Code,
	Copy,
	ExternalLink,
	Frown,
	GitBranch,
	Globe,
	Home,
	Info,
	Layers,
	Mail,
	MapPin,
	Menu,
	Moon,
	Palette,
	Phone,
	Search,
	Send,
	Sparkles,
	Sun,
	Terminal,
	Volume,
	Volume2,
	X
} from "lucide-react";

import { FaNetworkWired } from "react-icons/fa6";
import {
	SiAngular,
	SiBitbucket,
	SiCss,
	SiCypress,
	SiDart,
	SiElectron,
	SiExpress,
	SiFigma,
	SiFlutter,
	SiGit,
	SiGitlab,
	SiHibernate,
	SiHtml5,
	SiJavascript,
	SiJest,
	SiJson,
	SiJunit5,
	SiMongodb,
	SiMysql,
	SiNextdotjs,
	SiNodedotjs,
	SiOpenai,
	SiOpenjdk,
	SiPostgresql,
	SiPostman,
	SiPrimefaces,
	SiPython,
	SiReact,
	SiSass,
	SiSpring,
	SiSpringboot,
	SiTailwindcss,
	SiTypescript,
	SiVuedotjs,
	SiXml,
	SiYaml
} from "react-icons/si";

export const FALLBACK_ICON = Frown;

export const ICONS_NAME = {
	ALERT_ERROR: "alert-circle",
	ALERT_WARNING: "alert-warning",
	ANGULAR: "angular",
	AUDIO_ACTIVE: "audio-active",
	AUDIO_BASE: "audio-base",
	AWARD: "award",
	BITBUCKET: "bitbucket",
	BOOK: "book",
	BRIEFCASE: "briefcase",
	BUILDING: "building",
	CHECK: "check",
	CHECK_CIRCLE: "check-circle",
	CHEVRONDOWN: "chevron-down",
	CHEVRONUP: "chevron-up",
	CLOSE: "close",
	CODE: "code",
	COPY: "copy",
	CSS: "css",
	CURATORS_LOUPE: "curators-loupe",
	CYPRESS: "cypress",
	DART: "dart",
	ELECTRON: "electron",
	EXPRESS: "express",
	EXTERNAL_LINK: "externallink",
	FIGMA: "figma",
	FLUTTER: "flutter",
	GIT: "git",
	GITBRANCH: "gitbranch",
	GITHUB: "github",
	GITLAB: "gitlab",
	GLOBE: "globe",
	GLOBE_IN_A_BOX: "globe-in-a-box",
	HIBERNATE: "hibernate",
	HOME: "home",
	HTML: "html",
	INFO: "info",
	JAVA: "java",
	JAVASCRIPT: "javascript",
	JEST: "jest",
	JSON: "json",
	JUNIT: "junit",
	LINKEDIN: "linkedin",
	LAYERS: "layers",
	MAIL: "mail",
	MAP_PIN: "map-pin",
	MENU: "menu",
	MONGO_DB: "mongodb",
	MOON: "moon",
	MYSQL: "mysql",
	NETWORK_WIRED: "network-wired",
	NEXT_DOT_JS: "nextdotjs",
	NODE: "node",
	OPENAPI: "openapi",
	PALETTE: "palette",
	PHONE: "phone",
	POSTGRESQL: "postgresql",
	POSTMAN: "postman",
	PRIMEFACES: "primefaces",
	PYTHON: "python",
	REACT: "react",
	SASS: "sass",
	SEARCH: "search",
	SEND: "send",
	SPARKLES: "sparkles",
	SPINNER: "spinner",
	SPRING_BOOT: "spring-boot",
	SPRING_FRAMEWORK: "spring-framework",
	SUN: "sun",
	TAILWINDCSS: "tailwindcss",
	TERMINAL: "terminal",
	TIMELINE_GALLERY: "timeline-gallery",
	TYPESCRIPT: "typescript",
	VUE: "vue",
	WARNING: "warning",
	X: "x",
	XML: "xml",
	YAML: "yaml"
} as const;

export type IconName = typeof ICONS_NAME[keyof typeof ICONS_NAME];

export const ICONS_BY_NAME: Record<IconName, ElementType> = {
	"alert-circle": AlertCircleIcon,
	"alert-warning": AlertTriangleIcon,
	angular: SiAngular,
	"audio-active": Volume2,
	"audio-base": Volume,
	award: Award,
	bitbucket: SiBitbucket,
	book: Book,
	briefcase: Briefcase,
	building: Building2,
	check: Check,
	"check-circle": CheckCircle,
	"chevron-down": ChevronDown,
	"chevron-up": ChevronUp,
	close: X,
	code: Code,
	copy: Copy,
	css: SiCss,
	"curators-loupe": lazy(() => import("./svg/curatorsLoupeSvg")),
	cypress: SiCypress,
	dart: SiDart,
	electron: SiElectron,
	express: SiExpress,
	externallink: ExternalLink,
	figma: SiFigma,
	flutter: SiFlutter,
	git: SiGit,
	gitbranch: GitBranch,
	github: lazy(() => import("./svg/githubSvg")),
	gitlab: SiGitlab,
	globe: Globe,
	"globe-in-a-box": lazy(() => import("./svg/globeInABoxSvg")),
	hibernate: SiHibernate,
	home: Home,
	html: SiHtml5,
	info: Info,
	java: SiOpenjdk,
	javascript: SiJavascript,
	jest: SiJest,
	json: SiJson,
	junit: SiJunit5,
	layers: Layers,
	linkedin: lazy(() => import("./svg/linkedInSvg")),
	mail: Mail,
	"map-pin": MapPin,
	menu: Menu,
	mongodb: SiMongodb,
	moon: Moon,
	mysql: SiMysql,
	"network-wired": FaNetworkWired,
	"nextdotjs": SiNextdotjs,
	node: SiNodedotjs,
	openapi: SiOpenai,
	palette: Palette,
	phone: Phone,
	postgresql: SiPostgresql,
	postman: SiPostman,
	primefaces: SiPrimefaces,
	python: SiPython,
	react: SiReact,
	sass: SiSass,
	search: Search,
	send: Send,
	sparkles: Sparkles,
	spinner: lazy(() => import("./svg/spinnerSvg")),
	"spring-boot": SiSpringboot,
	"spring-framework": SiSpring,
	sun: Sun,
	tailwindcss: SiTailwindcss,
	terminal: Terminal,
	"timeline-gallery": lazy(() => import("./svg/timelineGallerySvg")),
	typescript: SiTypescript,
	vue: SiVuedotjs,
	warning: AlertTriangleIcon,
	x: X,
	xml: SiXml,
	yaml: SiYaml
} as const;
